/**
 * Auto Memory Service
 * Automatically creates Memory records from key events:
 * - Affection milestones (100, 300, 500, 700, 900)
 * - Relationship stage changes
 * - Level milestones (every 5 levels)
 */

import { prisma } from '../../lib/prisma';
import { RelationshipStage } from '@prisma/client';
import { createModuleLogger } from '../../lib/logger';

const log = createModuleLogger('AutoMemory');

const AFFECTION_MILESTONES = [100, 300, 500, 700, 900];

const AFFECTION_MILESTONE_TITLES: Record<number, { title: string; description: string }> = {
  100: {
    title: 'Những bước đầu tiên 💫',
    description: 'Đạt 100 điểm tình cảm - bắt đầu gần gũi hơn với nhau.',
  },
  300: {
    title: 'Tình bạn đặc biệt 🌟',
    description: 'Đạt 300 điểm tình cảm - mối quan hệ ngày càng thân thiết.',
  },
  500: {
    title: 'Gần gũi hơn bao giờ 💕',
    description: 'Đạt 500 điểm tình cảm - hai người đã thực sự hiểu nhau.',
  },
  700: {
    title: 'Tình cảm sâu đậm ❤️',
    description: 'Đạt 700 điểm tình cảm - cảm xúc ngày càng mạnh mẽ và chân thành.',
  },
  900: {
    title: 'Yêu nhau thật sự 💖',
    description: 'Đạt 900 điểm tình cảm - tình yêu sâu sắc và vô điều kiện.',
  },
};

const STAGE_TITLES: Partial<Record<RelationshipStage, { title: string; description: string }>> = {
  ACQUAINTANCE: {
    title: 'Bắt đầu quen biết 🤝',
    description: 'Chính thức bước vào giai đoạn quen biết - một khởi đầu mới.',
  },
  FRIEND: {
    title: 'Trở thành bạn bè 😊',
    description: 'Mối quan hệ tiến lên giai đoạn bạn bè - tin tưởng và chia sẻ.',
  },
  CLOSE_FRIEND: {
    title: 'Bạn thân của nhau 💙',
    description: 'Giai đoạn bạn thân - hai người hiểu nhau sâu sắc.',
  },
  CRUSH: {
    title: 'Bắt đầu có tình cảm 💗',
    description: 'Giai đoạn thầm thương - cảm xúc đặc biệt bắt đầu nảy sinh.',
  },
  DATING: {
    title: 'Chính thức hẹn hò 💕',
    description: 'Chính thức trở thành người yêu - một cột mốc đáng nhớ!',
  },
  IN_LOVE: {
    title: 'Đang yêu nhau ❤️',
    description: 'Giai đoạn đang yêu - tình cảm nồng nàn và say đắm.',
  },
  LOVER: {
    title: 'Người yêu của nhau 💖',
    description: 'Đạt đến đỉnh cao của tình yêu - gắn bó sâu sắc và bền vững.',
  },
};

export const autoMemoryService = {
  /**
   * Check if affection crossed any milestone and create memory if so.
   */
  async checkAffinityMilestone(
    userId: string,
    characterId: string,
    previousAffection: number,
    newAffection: number
  ): Promise<void> {
    for (const milestone of AFFECTION_MILESTONES) {
      if (previousAffection < milestone && newAffection >= milestone) {
        const info = AFFECTION_MILESTONE_TITLES[milestone];
        try {
          // Check if milestone memory already exists to avoid duplicates
          const existing = await prisma.memory.findFirst({
            where: { userId, characterId, milestone: `affection_${milestone}` },
          });
          if (existing) continue;

          await prisma.memory.create({
            data: {
              userId,
              characterId,
              title: info.title,
              description: info.description,
              type: 'MILESTONE',
              milestone: `affection_${milestone}`,
              isAutoGenerated: true,
              autoGenSource: 'milestone',
            },
          });
          log.info(`Created affection milestone memory at ${milestone} for char ${characterId}`);
        } catch (error) {
          log.error(`Error creating milestone memory at ${milestone}:`, error);
        }
      }
    }
  },

  /**
   * Auto-create memory when relationship stage changes.
   */
  async createRelationshipStageMemory(
    userId: string,
    characterId: string,
    newStage: RelationshipStage
  ): Promise<void> {
    const info = STAGE_TITLES[newStage];
    if (!info) return;

    try {
      // Check if stage memory already exists to avoid duplicates
      const existing = await prisma.memory.findFirst({
        where: { userId, characterId, milestone: `stage_${newStage.toLowerCase()}` },
      });
      if (existing) return;

      await prisma.memory.create({
        data: {
          userId,
          characterId,
          title: info.title,
          description: info.description,
          type: 'MILESTONE',
          milestone: `stage_${newStage.toLowerCase()}`,
          isAutoGenerated: true,
          autoGenSource: 'stage_change',
        },
      });
      log.info(`Created stage change memory: ${newStage} for char ${characterId}`);
    } catch (error) {
      log.error(`Error creating stage memory for ${newStage}:`, error);
    }
  },

  /**
   * Auto-create memory when leveling up (only at milestone levels: 5, 10, 15...).
   */
  async createLevelUpMemory(
    userId: string,
    characterId: string,
    newLevel: number
  ): Promise<void> {
    if (newLevel % 5 !== 0) return;

    try {
      const existing = await prisma.memory.findFirst({
        where: { userId, characterId, milestone: `level_${newLevel}` },
      });
      if (existing) return;

      await prisma.memory.create({
        data: {
          userId,
          characterId,
          title: `Đạt Level ${newLevel}! 🎉`,
          description: `Cùng nhau đạt đến level ${newLevel} - mối quan hệ ngày càng sâu sắc và bền chặt hơn.`,
          type: 'EVENT',
          milestone: `level_${newLevel}`,
          isAutoGenerated: true,
          autoGenSource: 'level_up',
        },
      });
      log.info(`Created level up memory at level ${newLevel} for char ${characterId}`);
    } catch (error) {
      log.error(`Error creating level up memory at ${newLevel}:`, error);
    }
  },
};
