-- AlterTable: Add isAutoGenerated and autoGenSource columns to memories (were in schema but missing migration)
ALTER TABLE "memories" ADD COLUMN IF NOT EXISTS "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "memories" ADD COLUMN IF NOT EXISTS "autoGenSource" TEXT;

-- CreateIndex: Add index for userId + isAutoGenerated (was in schema but missing migration)
CREATE INDEX IF NOT EXISTS "memories_userId_isAutoGenerated_idx" ON "memories"("userId", "isAutoGenerated");
